USE UNIVER

SELECT f.FACULTY,g.IDGROUP, COUNT(s.IDSTUDENT)

FROM FACULTY f inner join GROUPS g on f.FACULTY=g.FACULTY inner join STUDENT s on g.IDGROUP = s.IDGROUP

GROUP BY ROLLUP (f.FACULTY,g.IDGROUP)