USE UNIVER

SELECT f.FACULTY, g.PROFESSION, p.SUBJECT, ROUND(AVG(CAST(p.NOTE as float(4))),2) [Средняя оценка] 

FROM FACULTY f inner join GROUPS g on f.FACULTY = g.FACULTY
inner join STUDENT s on g.IDGROUP = s.IDGROUP
inner join PROGRESS p on s.IDSTUDENT = p.IDSTUDENT

WHERE f.FACULTY = 'ИТ'

GROUP BY f.FACULTY,g.PROFESSION,p.SUBJECT

USE UNIVER

SELECT f.FACULTY, g.PROFESSION, p.SUBJECT, ROUND(AVG(CAST(p.NOTE as float(4))),2) [Средняя оценка] 

FROM FACULTY f inner join GROUPS g on f.FACULTY = g.FACULTY
inner join STUDENT s on g.IDGROUP = s.IDGROUP
inner join PROGRESS p on s.IDSTUDENT = p.IDSTUDENT

WHERE f.FACULTY = 'ИТ'

GROUP BY CUBE (f.FACULTY,g.PROFESSION,p.SUBJECT)