SELECT        FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION, STUDENT.NAME, PROGRESS.NOTE,
CASE
	when (PROGRESS.NOTE = 6) then 'רוסעü'
	when (PROGRESS.NOTE = 7) then 'סולü'
	when (PROGRESS.NOTE = 8) then 'גמסולü'
	
END
FROM            STUDENT INNER JOIN
                         PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT CROSS JOIN
                         FACULTY INNER JOIN
                         PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY INNER JOIN
                         PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY 

WHERE PROGRESS.NOTE between 6 and 8
ORDER BY 
(CASE
	when (PROGRESS.NOTE = 6) then 1
	when (PROGRESS.NOTE = 7) then 2
	when (PROGRESS.NOTE = 8) then 3
END
)
						 
