USE UNIVER

SELECT FACULTY.FACULTY, PULPIT.PULPIT, GROUPS.PROFESSION,  SUBJECT.SUBJECT_NAME, STUDENT.NAME, PROGRESS.NOTE,
CASE
	when (PROGRESS.NOTE = 6) then 'רוסעü'
	when (PROGRESS.NOTE = 7) then 'סולü'
	when (PROGRESS.NOTE = 8) then 'גמסולü'
	
END 
FROM    FACULTY inner join PULPIT on FACULTY.FACULTY = PULPIT.FACULTY 
		inner join SUBJECT on PULPIT.PULPIT = SUBJECT.PULPIT
		inner join PROGRESS on SUBJECT.SUBJECT = PROGRESS.SUBJECT
		inner join STUDENT on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP

WHERE PROGRESS.NOTE between 6 and 8 
ORDER BY 
(CASE
	WHEN (PROGRESS.NOTE=6) then 1
	WHEN (PROGRESS.NOTE=7) then 2
	WHEN (PROGRESS.NOTE=8) then 3
END
)

	


						 
