USE UNIVER

SELECT PULPIT.PULPIT_NAME
FROM TEACHER FULL OUTER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT isnull(TEACHER.TEACHER_NAME,'«ацеплю €гу, л€гу в гроб')
FROM PULPIT FULL OUTER JOIN TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
FROM TEACHER FULL OUTER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT


SELECT PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
FROM TEACHER INNER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
FROM TEACHER LEFT OUTER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
FROM TEACHER RIGHT OUTER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT