USE UNIVER

SELECT PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
FROM TEACHER FULL OUTER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT isnull(TEACHER.TEACHER_NAME,'***'), PULPIT.PULPIT_NAME
FROM TEACHER FULL OUTER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT