USE UNIVER
SELECT  AUDITORIUM.AUDITORIUM, TIMETABLE.DAY,TIMETABLE.PARA
FROM AUDITORIUM LEFT OUTER JOIN TIMETABLE ON AUDITORIUM.AUDITORIUM=TIMETABLE.AUDITORIUM and TIMETABLE.DAY='2022-03-01'

SELECT  TEACHER.TEACHER_NAME, TIMETABLE.DAY,TIMETABLE.PARA
FROM TEACHER LEFT OUTER JOIN TIMETABLE ON TEACHER.TEACHER=TIMETABLE.TEACHER and TIMETABLE.DAY='2022-03-01'