SELECT TOP 1
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'нюХо'),
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'йц'),
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'ясад')
	FROM PROGRESS
