USE UNIVER

SELECT PULPIT.PULPIT_NAME
FROM PULPIT,FACULTY
WHERE PULPIT.FACULTY = FACULTY.FACULTY
and FACULTY.FACULTY IN 
(SELECT PROFESSION.FACULTY 
 FROM PROFESSION 
 WHERE(PROFESSION.PROFESSION_NAME LIKE '%технология%' OR PROFESSION.PROFESSION_NAME LIKE '%технологии%'))