USE UNIVER

SELECT NAME,BDAY
FROM STUDENT a
WHERE BDAY = ANY (SELECT BDAY FROM STUDENT aa where aa.NAME!=a.NAME)
ORDER BY a.BDAY ASC

USE UNIVER

SELECT NAME,BDAY
FROM STUDENT a
WHERE BDAY IN (SELECT BDAY FROM STUDENT aa where aa.BDAY IN (a.BDAY) and aa.NAME!=a.NAME)
ORDER BY a.BDAY ASC