USE UNIVER
SELECT DISTINCT PULPIT.PULPIT_NAME
FROM PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY = FACULTY.FACULTY
INNER JOIN PROFESSION
ON PROFESSION.FACULTY = FACULTY.FACULTY 
WHERE PROFESSION.PROFESSION_NAME LIKE '%технология%' OR PROFESSION.PROFESSION_NAME LIKE '%технологии%'

