SELECT TOP 1
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'нюХо') [нюХо],
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'йц') [йц],
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'ясад') [ад]
	FROM PROGRESS
