USE UNIVER;

SELECT A.IDSTUDENT, A.NOTE
FROM PROGRESS AS A
WHERE A.NOTE >= ALL (SELECT B.NOTE 
					  FROM PROGRESS AS B
					  WHERE A.IDSTUDENT != B.IDSTUDENT);
SELECT A.IDSTUDENT, A.NOTE
FROM PROGRESS AS A
WHERE A.NOTE >= ANY (SELECT B.NOTE 
					  FROM PROGRESS AS B
					  WHERE A.IDSTUDENT != B.IDSTUDENT);