USE UNIVER 
GO

ALTER FUNCTION FCTEACHER(@p varchar(50)) RETURNS INT AS
	BEGIN
		DECLARE @rc int = (SELECT count(*) FROM TEACHER WHERE PULPIT=isnull(@p,PULPIT)) 
		RETURN @Rc
	END
GO
SELECT PULPIT,dbo.FCTEACHER(PULPIT)[Преподователей] FROM PULPIT
SELECT dbo.FCTEACHER(NULL) [Всего преподователей]