CREATE TRIGGER TRANS_TRIGGER on TEACHER after INSERT,UPDATE,DELETE AS
	DECLARE @c int = (SELECT count(*) FROM TEACHER WHERE TEACHER ='');
	if(@c > 0)
	BEGIN
		RAISERROR('Имя не может быть пустым',10,1);
		ROLLBACK;
	END;
	RETURN;
GO

UPDATE TEACHER SET TEACHER ='' WHERE TEACHER='ЛДИ'