CREATE TABLE AUDITORIUM
( AUDITORIUM char(20) primary key,
	AUDITORIUM_TYPE char(10),
	AUDITORIUM_CAPACITY int default 1 CHECK (AUDITORIUM_CAPACITY between 1 and 300),
	AUDITORIUM_NAME varchar(50)
) ON FG1